### ISSUE TITLE
Error: Cannot find module 'svelte/store.mjs'

### ISSUE THREAD

**Issue by rob-balfre** [mightyjol/sapper-firebase-template#5]
After following the setup guide I get the error `Error: Cannot find module 'svelte/store.mjs'` when trying to run `yarn dev`

**Comment by mortscode** [comment]
Same issue

**Comment by rob-balfre** [comment]
Respecting the yarn.lock file is the solution.  Svelte and Sapper are out of sync otherwise.

**Comment by mortscode** [comment]
@rob-balfre what do you mean by "respecting"? Can I just delete it and re-install the dependencies?

**Comment by rob-balfre** [comment]
@mortscode I had to use the lock file that is currently in this repo (don't delete or manually upgrade anything) and use yarn and not npm.  The problem arose out of my Svelte and Sapper version being incompatible. From discord chat yesterday... 

> I'm guessing it's because you're getting Svelte >= 3.5.0 but aren't getting Sapper >= 0.27.3
> https://github.com/sveltejs/sapper/blob/master/CHANGELOG.md#0273
> There were internal changes in Svelte 3.5.0 that were supposed to not be very breaking, but they did require changes in Sapper
> If you're installing with something other than Yarn, you won't be respecting their lock file, and the Svelte ^3.0.0 range would end up giving you too new of a version for the Sapper ^0.26 range
> 

>

**Comment by rob-balfre** [comment]
Also worth noting (not tried this yet)... 

> @rob_b I started with this firebase template as well, upgraded svelte to 361 and sapper to 0274 today and it works fine
fb version is 623
fb admin 820

**Comment by mortscode** [comment]
Yeah, I saw those version updates and still struggling. I've been trying to make it work with NPM. I'll give yarn a go.

**Comment by rob-balfre** [comment]
@mortscode good luck

**Comment by mortscode** [comment]
Ok. I think I'm almost there. Strange issue where my assets aren't making their way down from firebase to my local. So I'm just getting the html with no assets or styles. Borat's jpg and global.css aren't in my `static` folder so I'm assuming it's not making its way down from the hosting server on firebase.

Any thoughts?

<img width="1120" alt="Screen Shot 2019-06-26 at 3 13 36 PM" src="https://user-images.githubusercontent.com/3239582/60218712-0369fb80-9825-11e9-80a1-27d108502e83.png">

**Comment by mortscode** [comment]
I'm getting this when I run `firebase serve`:
```
[warn] ⚠  Error: Cannot find module './__sapper__/build/server/server'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/scotmortimer/Development/Instrument/Burgerweek/sapper-firebase-template/functions/index.js:5:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
[warn] ⚠  We were unable to load your functions code. (see above)
```

**Comment by mortscode** [comment]
ok. up and running. it was lots of things, but got it all sorted out.
